version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8000:8000"

  web:
    build: .
    ports:
      - "5000:5000"  # Flask port, use 8000 for Django
    environment:
      DB_HOST: db
      DB_NAME: myapp
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db
