services:
  db:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mariadb_data:
