services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: CareConnect
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
